kind: pipeline
name: braid

steps:
    - name: build
      image: golang:1.13.3
      commands:
        - pwd
        - export GOPROXY=https://goproxy.io
        - export MOCK_REDIS_ADDR=redis://172.16.208.30:6379/0
        - export MOCK_CONSUL_ADDR=http://172.16.208.30:8900
        - export MOCK_JAEGER_ADDR=http://172.16.208.30:9411/api/v2/spans
        - go version
        - go test ./...
